<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <Version>0.3.1</Version>
    <Product>Aion2Dps</Product>
    <Company>aion2dps</Company>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
</Project>
