using Aion2Dps.App.Settings;

namespace Aion2Dps.App.Theming;

/// <summary>The built-in themes: the default "Obsidian" plus six alternatives. All names and palettes are original.</summary>
public static class ThemeCatalog
{
    public const string DefaultId = "obsidian";

    private static Color C(string hex) => ColorUtil.Parse(hex);

    public static readonly ThemeDefinition Obsidian = new()
    {
        Id = "obsidian",
        Name = "Obsidian",
        Description = "Default. Smoked charcoal with warm gold accents.",
        WindowBackground = C("#E8121418"),
        Surface = C("#1C1F25"),
        SurfaceAlt = C("#272B33"),
        Border = C("#3D3629"),
        Text = C("#EFE9DC"),
        TextMuted = C("#9D9685"),
        Accent = C("#D9A441"),
        AccentText = C("#1A1408"),
        Positive = C("#6CCB7E"),
        Negative = C("#E5605A"),
        Warning = C("#E8B04A"),
        Crit = C("#FFCF5C"),
        Dot = C("#B07CF0"),
        Heal = C("#63D3A0"),
        BarTrack = C("#1FFFFFFF"),
        BarFill = C("#D9A441"),
        HpHigh = C("#C23E3A"),
        HpMid = C("#DD8530"),
        HpLow = C("#F2C94C"),
        HeaderTop = C("#F02A2418"),
        HeaderBottom = C("#00161820"),
        DashboardBackground = C("#131519"),
        FontFamily = "Segoe UI",
        MonoFontFamily = "Bahnschrift",
        CornerRadius = 6,
        BarCornerRadius = 2,
    };

    public static readonly ThemeDefinition Glacier = new()
    {
        Id = "glacier",
        Name = "Glacier",
        Description = "Frosted glass: translucent blue-grey panes, icy cyan highlights.",
        WindowBackground = C("#991A2633"),
        Surface = C("#2AFFFFFF"),
        SurfaceAlt = C("#40FFFFFF"),
        Border = C("#70BFE6FF"),
        Text = C("#F4FAFF"),
        TextMuted = C("#AEC6DA"),
        Accent = C("#7FD8F7"),
        AccentText = C("#0B2230"),
        Positive = C("#7DE3B5"),
        Negative = C("#FF7A8A"),
        Warning = C("#FFD27A"),
        Crit = C("#FFE08A"),
        Dot = C("#C59BFF"),
        Heal = C("#7DE3C8"),
        BarTrack = C("#24FFFFFF"),
        BarFill = C("#7FD8F7"),
        HpHigh = C("#5AB4E8"),
        HpMid = C("#9C8CF0"),
        HpLow = C("#F07AA8"),
        HeaderTop = C("#38FFFFFF"),
        HeaderBottom = C("#08FFFFFF"),
        DashboardBackground = C("#18232F"),
        FontFamily = "Segoe UI",
        MonoFontFamily = "Segoe UI Semibold",
        CornerRadius = 10,
        BarCornerRadius = 4,
    };

    public static readonly ThemeDefinition Ember = new()
    {
        Id = "ember",
        Name = "Ember",
        Description = "Banked coals: deep umber with molten orange.",
        WindowBackground = C("#EB1A100D"),
        Surface = C("#251814"),
        SurfaceAlt = C("#311F19"),
        Border = C("#5C301E"),
        Text = C("#F8EADF"),
        TextMuted = C("#B59C8B"),
        Accent = C("#FF7A3D"),
        AccentText = C("#220C02"),
        Positive = C("#9BD86C"),
        Negative = C("#FF5A4F"),
        Warning = C("#FFB347"),
        Crit = C("#FFD166"),
        Dot = C("#C77DFF"),
        Heal = C("#6EE0A8"),
        BarTrack = C("#22FFFFFF"),
        BarFill = C("#FF7A3D"),
        HpHigh = C("#E2463A"),
        HpMid = C("#FF8C2E"),
        HpLow = C("#FFD23F"),
        HeaderTop = C("#F03D1B10"),
        HeaderBottom = C("#001A100D"),
        DashboardBackground = C("#170E0B"),
        FontFamily = "Segoe UI",
        MonoFontFamily = "Bahnschrift",
        CornerRadius = 4,
        BarCornerRadius = 2,
    };

    public static readonly ThemeDefinition Arcade = new()
    {
        Id = "arcade",
        Name = "Arcade",
        Description = "Broadcast neon: hard edges, magenta frame, cyan bars.",
        WindowBackground = C("#F20A0A18"),
        Surface = C("#15152B"),
        SurfaceAlt = C("#202042"),
        Border = C("#FF2E88"),
        Text = C("#F3F3FF"),
        TextMuted = C("#9393C6"),
        Accent = C("#00E5FF"),
        AccentText = C("#001218"),
        Positive = C("#39FF88"),
        Negative = C("#FF3366"),
        Warning = C("#FFE600"),
        Crit = C("#FFE600"),
        Dot = C("#B26BFF"),
        Heal = C("#39FFC8"),
        BarTrack = C("#1CFFFFFF"),
        BarFill = C("#00E5FF"),
        HpHigh = C("#FF2E88"),
        HpMid = C("#FF8A00"),
        HpLow = C("#FFE600"),
        HeaderTop = C("#FF3A0B4A"),
        HeaderBottom = C("#000A0A18"),
        DashboardBackground = C("#0B0B19"),
        FontFamily = "Bahnschrift",
        MonoFontFamily = "Bahnschrift",
        CornerRadius = 0,
        BarCornerRadius = 0,
        DefaultBarStyle = BarStyle.Solid,
    };

    public static readonly ThemeDefinition Abyssal = new()
    {
        Id = "abyssal",
        Name = "Abyssal",
        Description = "Dark violet depths with blood-red highlights.",
        WindowBackground = C("#EA140B18"),
        Surface = C("#1F1325"),
        SurfaceAlt = C("#2B1933"),
        Border = C("#552446"),
        Text = C("#F1E5F3"),
        TextMuted = C("#A790B1"),
        Accent = C("#D23C64"),
        AccentText = C("#FFFFFF"),
        Positive = C("#74D29A"),
        Negative = C("#FF5470"),
        Warning = C("#F2A65A"),
        Crit = C("#FF8FB1"),
        Dot = C("#A979FF"),
        Heal = C("#6FD6B0"),
        BarTrack = C("#22FFFFFF"),
        BarFill = C("#D23C64"),
        HpHigh = C("#8E3BD6"),
        HpMid = C("#C83C8C"),
        HpLow = C("#FF5470"),
        HeaderTop = C("#F038122F"),
        HeaderBottom = C("#00140B18"),
        DashboardBackground = C("#120A15"),
        FontFamily = "Segoe UI",
        MonoFontFamily = "Bahnschrift",
        CornerRadius = 8,
        BarCornerRadius = 3,
    };

    public static readonly ThemeDefinition Daybreak = new()
    {
        Id = "daybreak",
        Name = "Daybreak",
        Description = "Light parchment with amber trim, for bright scenes.",
        IsDark = false,
        WindowBackground = C("#F2FAF7EF"),
        Surface = C("#FFFFFF"),
        SurfaceAlt = C("#EFE9DA"),
        Border = C("#D6CBB2"),
        Text = C("#2A251C"),
        TextMuted = C("#776E5C"),
        Accent = C("#B57D1C"),
        AccentText = C("#FFFFFF"),
        Positive = C("#2E9E5B"),
        Negative = C("#C8423A"),
        Warning = C("#B97D0C"),
        Crit = C("#B87400"),
        Dot = C("#7B4FC9"),
        Heal = C("#1E9C78"),
        BarTrack = C("#16000000"),
        BarFill = C("#D9A441"),
        HpHigh = C("#C8423A"),
        HpMid = C("#DE8A25"),
        HpLow = C("#E2B523"),
        HeaderTop = C("#FFFFF3D9"),
        HeaderBottom = C("#00FAF7EF"),
        DashboardBackground = C("#F4F0E6"),
        FontFamily = "Segoe UI",
        MonoFontFamily = "Bahnschrift",
        CornerRadius = 8,
        BarCornerRadius = 3,
        ClassColors = new Dictionary<CharacterClass, Color>
        {
            [CharacterClass.Cleric] = C("#D2AE2A"),
            [CharacterClass.Chanter] = C("#4FA7DE"),
            [CharacterClass.Elementalist] = C("#1FA5AE"),
        },
    };

    public static readonly ThemeDefinition Wisp = new()
    {
        Id = "wisp",
        Name = "Wisp",
        Description = "Minimal and translucent: just text and thin bars over the game.",
        WindowBackground = C("#66000000"),
        Surface = C("#30000000"),
        SurfaceAlt = C("#4A000000"),
        Border = C("#00FFFFFF"),
        Text = C("#FFFFFF"),
        TextMuted = C("#CCFFFFFF"),
        Accent = C("#FFFFFF"),
        AccentText = C("#000000"),
        Positive = C("#8DF0B0"),
        Negative = C("#FF8A8A"),
        Warning = C("#FFD98A"),
        Crit = C("#FFE9A0"),
        Dot = C("#D4B5FF"),
        Heal = C("#9CF5D8"),
        BarTrack = C("#22FFFFFF"),
        BarFill = C("#C0FFFFFF"),
        HpHigh = C("#F0F0F0"),
        HpMid = C("#FFD98A"),
        HpLow = C("#FF8A8A"),
        HeaderTop = C("#00000000"),
        HeaderBottom = C("#00000000"),
        DashboardBackground = C("#1C1D21"),
        FontFamily = "Segoe UI",
        MonoFontFamily = "Segoe UI Semibold",
        CornerRadius = 12,
        BarCornerRadius = 2,
        DefaultBarStyle = BarStyle.Slim,
    };

    public static IReadOnlyList<ThemeDefinition> All { get; } = [Obsidian, Glacier, Ember, Arcade, Abyssal, Daybreak, Wisp];

    public static ThemeDefinition? Find(string? id) =>
        All.FirstOrDefault(t => string.Equals(t.Id, id, StringComparison.OrdinalIgnoreCase));

    public static ThemeDefinition Get(string? id) => Find(id) ?? Obsidian;
}
